# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pickle and release save

on:
  push:
    branches: [ "main" ]
    tags: "v*"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  pickle-and-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    - name: Pickle the save
      env:
        YARPE_VERSION: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
      run: |
        python3 pack_savegame.py
        python3 pack_unzipper.py
        mv 1-1-LT1_unzipper.save 1-1-LT1.save
    - name: Upload save to artifact
      uses: actions/upload-artifact@v4
      with:
        name: savefile
        path: |
          ./save.zip
          ./1-1-LT1.save
    - name: Create release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        body: |
          Read [README](./README.md) for usage.
        files: |
          ./save.zip
          ./1-1-LT1.save
